<?php
if($_SERVER['HTTP_HOST'] == 'admin.onlineaushadhi.dev' || $_SERVER['HTTP_HOST'] == '127.0.0.1')
{
	define("DBSERVER","localhost");
	define("DBUSER","root");
	define("DBPASSW","");
	define("DBNAME","onlineaushadhi");
}
else
{
	define("DBSERVER","localhost");
	/*define("DBUSER","onlineau_pharmac");
	define("DBPASSW","oRefXD+KF;BB");
	define("DBNAME","onlineau_pharmacy");
	define("DBUSER","onlineau_demousr");
	define("DBPASSW","kfkMJ752]J;L");
	define("DBNAME","onlineau_demo");*/
	define("DBUSER","onlineaushadhi");
	define("DBPASSW","");
	define("DBNAME","root");
}
?>